services:
  - type: web
    name: authflowx-api
    runtime: docker
    plan: free

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authflowx-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

      - key: REDIS_URL
        fromService:
          type: redis
          name: authflowx-redis
          property: connectionString

databases:
  - name: authflowx-db
    plan: free

redis:
  - name: authflowx-redis
    plan: free